name: Race Tests

on:
  push:
    tags:
    branches:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.5
          cache-dependency-path: |
            go.sum
            .github/cache-key-for-race-test

      - name: Test
        run: go test -race -v ./...
